version: '3.8'
services:
  web:
    build: .
    ports:
      - "7860:7860"
    environment:
      - REDIS_URL=${REDIS_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - redis
  redis:
    image: redis:7
    ports:
      - "6379:6379"
